import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import LayoutShell from "../components/layout-shell";
import ThemeInitScript from "../components/theme-init-script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <ThemeInitScript />
      </head>
      <body className="min-h-full flex flex-col">
        <div className="app-gradient" />
        <div className="app-grain" />
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
